lootproject/website

utils/lists.ts
Add floorbags.market to marketsList
=> Add floorbags.market to marketsList

pages/faq.tsx, utils/lists.ts
Hi,
I was reading through the website and noticed few spelling mistakes. Let me know if this is helpful.
=> Fix Spellings in FAQ,  resource lists

utils/lists.ts
=> Add Treasure to derivative projects

utils/lists.ts
=> Add Name to project list

utils/lists.ts
Etherscan link: https://etherscan.io/address/0xab7f42a1a64f0f54d5428ab5e1243785bce3fcb3
Website: https://github.com/colorloot/colorloot
Twitter: https://twitter.com/lootavatars
=> Add color loot

utils/lists.ts
Team (for Loot) is randomized assembled team of adventurers for loot.
Contract address: https://etherscan.io/address/0xb0ce923d42ae2fc9572a1c69bce86a2451f4c667
=> Add Derivative: Team (for Loot)

utils/lists.ts
Etherscan link: https://etherscan.io/address/0xb71a6289b10236702b0514693a811f741f29955a
Website: https://loot-craft.com/
Twitter: https://twitter.com/craft_loot
Discord: https://discord.gg/jmNhdt6Zsb
=> Add Loot Materials

utils/lists.ts
The Upside Down is an alternate dimension existing in parallel to the human world. The history of the Upside Down remains a mystery. Exactly how and why it came into existence, is unclear.
It contains the same locations and infrastructure as the human world. There is little proven knowledge concerning the Upside Down, as it remains shrouded in mystery. In spite of this, the dimension possesses a few observable properties and characteristics. Such as, light, gravity, and sound appear to function the same way as in the regular world.
Etherscan link: https://etherscan.io/token/0x191dfb7e10f4c3a82b2c4f763d48744b6c7cf7ec
Website: https://upsidedownloot.com/
Twitter: https://twitter.com/UpsideDownLoot
Discord: WIP
=> Add Derivative: Upside Down Loot

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x8575B7dFE18F4c9A872253bB4f557AD02e94C3A5
Website: https://opensea.io/collection/landproject
Loot Land are parts of the world in Loot metaverse. LAND is divided into parcels that are referenced using unique x,y cartesian coordinates. Feel free to use Loot Land in any way you want.
refer #66
=> Add Loot Land

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x6f75edbfb41f94522eed734787fbc78c5688aa1e
Website: https://runesmystery.github.io/
Twitter: https://twitter.com/LootRunes
=> Add `Runes` to derivatives

utils/lists.ts
Etherscan link: https://etherscan.io/address/0xb71a6289b10236702b0514693a811f741f29955a
Website: https://loot-craft.com/
Twitter: https://twitter.com/craft_loot
Discord: https://discord.gg/jmNhdt6Zsb
=> Need fix with this typo

utils/lists.ts
Please use this pull request template when adding a new resource to the website. 
You do not have to fill out all the fields, but please attempt to complete as many as possible.
Please ensure:
1. Your contracts are verified ✅
2. If adding a resource, the name and description must fit on one line ✅ 
Thank you!
---
- Discord: https://discord.gg/fXKaNQJG
- Etherscan link: https://etherscan.io/address/0xf5dF2C0201Fd06fc5A387cCcBD70a1093AcB1455#writeContract
- Twitter: https://twitter.com/divinestats
- Opensea: https://opensea.io/collection/divine-stats
=> Add `Divine Stats` to list of derivatives

utils/lists.ts
Reverts lootproject/website#75
=> Revert "Add `Divine Stats` to list of derivatives"

utils/lists.ts
sexyLoot
Etherscan link: https://etherscan.io/address/0xb13EFaB167751A95EC6F9844944C74Aa668ddeD6#code
Website: https://sexyloot.co/
Twitter: https://twitter.com/LootSexy
=> Add sexyLoot

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x6Ce13E96CBaEF984496fBA4FDE0D3D48C8e30c25
Website: https://cangjie.art
Twitter: https://twitter.com/CangjieNFT
OpenSea: https://opensea.io/collection/cangjie
=> Add Derivative: Cangjie

utils/lists.ts
Updated lists.ts to add Playlists derivative project
Etherscan link: https://etherscan.io/address/0xc9ff11b733fcc652bbbfde5cbdc46aea007197e5#writeContract
Website: https://playlists-for-adventurers.carrd.co/
=> Adding Playlists derivative project

utils/lists.ts
Deck of Many Things
https://etherscan.io/address/0xb515bE4b1A1EF51b26bf268E96DB8FfFcE6b0Ff4#readContract
=> Add Deck of Many Things to derivative list

utils/lists.ts
Added SpaceLoot: Starship-themed Loot on Terra
Terra Finder link: https://finder.terra.money/columbus-4/address/terra1ec833xj9f8dm0c04cdka9fkyefzgll7pdzzyxq
Website: https://spaceloot.xyz/
Twitter: https://twitter.com/spaceloot_nft
=> Add SpaceLoot

pages/faq.tsx, utils/lists.ts
Etherscan link: https://etherscan.io/address/0x6b5f9713041f085af0f808e1445d8e6d38c51480
Website: https:// 
Twitter: https://twitter.com/PerksforAdvntr
Discord: https://discord.gg/zqZZZDXdmJ
=> Add Perks for Adventurers link

utils/lists.ts
Etherscan link: https://etherscan.io/address/ 
Website: https://mclues.io.ooo/
Twitter: https://twitter.com/HeaderChain
Discord: https://discord.gg/w4Vm6sj5
=> add Derivative Project MergeClues

utils/lists.ts
Through smart contracts you can stake your Loot and battle a monster. Battle results are determined by a dice roll (using Chainlink VRFs) and your Loot stats. By winning battles you can claim unique and rare items. Each monster drops a guaranteed item and might drop a rare card. Items are ERC1155 NFTs containing machine-generated pixel art.
Website: https://lootdungeon.app
Etherscan: https://etherscan.io/address/0xdc9d70e37662ce16615224efaa9bb2315b80e36b
OpenSea: https://opensea.io/collection/loot-dungeon
Twitter: https://twitter.com/LootDungeonApp
Discord: https://discord.gg/z6azBRgZ3J
=> Add Derivative: Loot Dungeon

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x90e9da69c4c77c6123e54d9e0e51c1603b3d09e4#writeContract 
Website: https://ethereum.castledao.com
Twitter: https://twitter.com/CastlesDAO2
Discord: https://discord.gg/nyKYmvnXca
=> change: Add CastleLoot

utils/lists.ts
Etherscan link: https://polygonscan.com/token/0x62d9fb7aa6dd88fa8c1be34442348b8e7ae5eb30 
Website: https://liferestartnft.github.io/
Twitter: https://twitter.com/LootLifeRestart
Discord: https://discord.com/
=> add a new Loot project

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x4deafaa0f5512afa1f7fa74fd83cb98c498f3d7a
Website: https://character-nft.vercel.app/
Twitter: https://twitter.com/DnD_NFT
Discord: https://discord.com/
=> change the Character's contract address to website URL.

utils/lists.ts
Dice is randomized weighted dice generated and stored on chain. Some dice are more fair, others are luckier.
Etherscan link: https://etherscan.io/address/0x4Cec6Dca972BB810A1af1Ef3C8366B22b390c5Bc
Website: https://diceforloot.com
Twitter: https://twitter.com/DiceForLoot
Discord: https://discord.gg/z6fbJcAADj
=> Add Derivative: Dice (for Loot)

utils/lists.ts
**Etherscan**: https://etherscan.io/address/0xb105ccFD786966c24DC011D6833b9636fD402504
**Website**: https://spellandtalent.noshit.dev/
**Twitter**: https://twitter.com/TalentSpell
**Discord**: https://discord.gg/fc9ftMK6
=> Added Spell & Talent Project to resources list

utils/lists.ts
Art (for Loot) has been added.
Website: https://opensea.io/collection/suprematism-regenesis
Twitter: https://twitter.com/lootzart
=> Add Derivative: Art (for Loot)

utils/lists.ts
The Genesis Project
Etherscan link: https://etherscan.io/token/0x8db687aceb92c66f013e1d614137238cc698fedb#writeProxyContract
Website: https://genesisproject.xyz/
Twitter: https://twitter.com/GenesisLoot
Discord: https://discord.com/invite/YUYyPSuwfU
OpenSea: https://opensea.io/collection/genesisadventurer
=> add The Genesis Project to derivatives

utils/lists.ts
hi, I'd like to update the link to point towards our DAO's webpage , and change the description .
=> update Genesis Project website link and description

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x1c653f203369ac9e67ba01fcf3ab5a509b6349d1
Website: https://opensea.io/collection/mekaloot
Twitter: https://twitter.com/meka_loot
=> Added MekaLoot

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x1308c158e60D7C4565e369Df2A86eBD853EeF2FB
Website: https://www.openpalette.io/
Twitter: https://twitter.com/open_pal
Discord: https://discord.gg/HWFNayQaDc
=> Add OpenPalette

utils/lists.ts
Etherscan link: https://etherscan.io/address/0x9B841F4741f99F0f04166C6F1828230d24C1613c
Website: https://www.abomnft.com/
Twitter: https://twitter.com/chrono_minter
=> Add Abominations derivative

README.md
Just update of the readme to reflect the new procedure.
=> first update on readme

utils/lists.ts
NPCs: Genesis Edition
Etherscan link: https://etherscan.io/address/0xB0C8E9982b879Bb955181aaeD158f1cDc4D10D05
Twitter: https://twitter.com/lootNPCs
=> Add NPCs: Genesis Edition to resources

utils/lists.ts
Vootloot
Etherscan link: https://polygonscan.com/token/0x43f061c0925d7162c73573d64c277aa741aa571c
Website: https://vootloot.com
Twitter: https://twitter.com/vootloot
Discord: https://discord.com/
=> update website url vootloot

utils/inspiredByLoot.ts, utils/lists.ts, utils/newLists.ts
Website: https://bannersnft.com/
Twitter: https://twitter.com/BannersNft
Discord: https://discord.gg/MYxGU7rjY4
=> Add Banners (for Adventures)

utils/newLists.ts, utils/projects.tsx
Etherscan link: https://etherscan.io/address/0x73c5013Fa9701425be4a436cA0CeC1C0898e6F14
Website: https://rings.market/
Twitter: https://twitter.com/RingsforLoot
=> Add Rings (for Loot) to the main page

utils/newLists.ts, utils/projects.tsx
Etherscan link: https://etherscan.io/address/0xC62934146bfcb6F3dDE478cbAb1E64a25fcC32eC#contracts
Website: https://lootpunk.org
Twitter: https://twitter.com/LootpunkProject
Discord: https://discord.gg/jKPZgRbs
=> [Lootpunk] Uploaded Lootpunk To Main Page

utils/projects.tsx
Etherscan link: https://etherscan.io/address/0x508d06b8f3a4b0fd363239ce61e0c4b0b82f3626
Website: https://lootexplorers.quest
Twitter: https://twitter.com/lootexplorers
=> Updated loot explorers minting soon to mint now

utils/inspiredByLoot.ts
Cryptoodles Loot Bag
Etherscan link: https://etherscan.io/address/0x2a16107ea0d28ae822168c8bb3ef5460b1924a78#code
Website: https://cryptoodles.com
Twitter: https://twitter.com/cryptoodles
Discord: https://discord.com/invite/g9SnvzdFs2
OpenSea: https://opensea.io/collection/toodle-loot-bag
=> Updated Cryptoodles project description

utils/lists.ts
The Crypt
Website: https://thecrypt.game/
Twitter: https://twitter.com/TheCryptGame
Discord: https://discord.com/invite/aMwetFaz6F
=> Added 'The Crypt' to the Lists.cs
